plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.graalvm.buildtools.native' version '0.11.5'
}

group = 'com.iaperfumeadvisor'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	// WEB

	implementation 'org.springframework.boot:spring-boot-starter-web'

	// JPA (BASE DE DATOS)

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// POSTGRESQL

	implementation 'org.postgresql:postgresql'

	// TEST

	testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

tasks.named('test') {
	useJUnitPlatform()
}
